base:
  project: winequality-project

data_source:
  data_url : 'https://drive.google.com/uc?id=1-4JALyI5ZkYpuYuoenDSw1eMEIlSWfml'
  directory_path : artifacts/data/
  random_state : 42

load_data:
  raw_dataset_path: artifacts/data/articles.csv
  train_path: artifacts/data/train.csv
  test_path: artifacts/data/test.csv
  val_path: artifacts/data/val.csv

estimators:
  num_labels: 21
  params:
    learning_rate: 0.00002
    train_batch_size: 16
    eval_batch_size: 16
    epochs: 10
    weight_decay: 0.01
    evaluation_strategy: epoch
    save_strategy: epoch
  model_dir: artifacts/model
